### PR TITLE
update csi and cpi images for k8s 1.28

### PR DESCRIPTION
**Pull request by thomasferrandiz**
#### Pull Request Checklist ####

- [x] Any new images or tags consumed by charts has been added [here](https://github.com/rancher/image-mirror)
- [x] Chart version has been incremented (if necessary)
- [ ] That helm lint and pack run successfully on the chart.
- [ ] Deployment of the chart has been tested and verified that it functions as expected.
- [ ] Changes to scripting or CI config have been tested to the best of your ability

#### After the PR is merged ####

Once the PR is merged, typically upon a new release, the necessary teams will be notified via Slack hook to perform the RKE2 Charts and RKE2 changes. Any developer working on this issue is not responsible for updating RKE2 Charts or RKE2.

### CODE REVIEW

**Comment by ElanHasson** [comment]
hi @thomasferrandiz,

Curious why not upgrade to latest version 3.1.x?

https://github.com/kubernetes-sigs/vsphere-csi-driver/releases?q=3.1&expanded=true

**Comment by thomasferrandiz** [comment]
Hi @ElanHasson 
sorry I missed your reply.

I have updated the chart and images to v3.1.2

**Comment by ElanHasson** [comment]
Thanks @thomasferrandiz !

**Comment by thomasferrandiz** [comment]
replaced by https://github.com/rancher/vsphere-charts/pull/64

**Pull request closed without merging**
