### PR TITLE
Add topology plugin value for rancher-vsphere-csi, update readme

### PR DESCRIPTION
**Pull request by dkeightley**
#### Pull Request Checklist ####

- N/A - Any new images or tags consumed by charts has been added [here](https://github.com/rancher/image-mirror)
- [x] Chart version has been incremented (if necessary)
- [x] That helm lint and pack run successfully on the chart.
- [x] Deployment of the chart has been tested and verified that it functions as expected.
- N/A Changes to scripting or CI config have been tested to the best of your ability

#### Types of Change ####

Add helm value to allow the CSI topology feature:
```yaml
topology:
  enabled: true
```

#### Linked Issues ####

https://github.com/rancher/rancher/issues/40727

### CODE REVIEW

**Review by jiaqiluo — APPROVED** [review]

**Review by brandond — APPROVED** [review]

**Comment by jiaqiluo** [comment]
hi @a-blender  , can yo review this this PR?

**Review by a-blender — APPROVED** [review]
How has this been tested?

**Comment by snasovich** [comment]
@dkeightley , I know this PR has been merged a while ago but wondering if we wanted this new field to be settable in the UI? If so, we want it included in `questions.yaml`.

**Comment by dkeightley** [comment]
> @dkeightley , I know this PR has been merged a while ago but wondering if we wanted this new field to be settable in the UI? If so, we want it included in `questions.yaml`.

This is a good idea, I think users would appreciate that, I'll raise a separate PR for consideration.

**Pull request merged**
