### PR TITLE
feat(rancher-vsphere-cpi): add labels option to vCenter 

### PR DESCRIPTION
**Pull request by secustor**
#### Pull Request Checklist ####

- [x] Any new images or tags consumed by charts has been added [here](https://github.com/rancher/image-mirror)
- [x] That helm lint and pack run successfully on the chart.
- [x] Deployment of the chart has been tested and verified that it functions as expected.
- [x] Changes to scripting or CI config have been tested to the best of your ability

#### Types of Change ####

- added the labels configuration to `vsphere.conf`. This allows to propagate regions and availability zones to nodes and the vSphere CSI
- use YAML instead of INI as this is recommended as of `v1.2.0`

#### Additional Notes ####

https://cloud-provider-vsphere.sigs.k8s.io/tutorials/kubernetes-on-vsphere-with-kubeadm.html
> NOTE: As of CPI version 1.2.0 or higher, the preferred cloud-config format will be YAML based. The INI based format will be deprecated but supported until the transition to the preferred YAML based configuration has been completed. This deprecation notice will be placed in the CPI logs when using the INI based configuration format.

#### After the PR is merged ####

Once the PR is merged, typically upon a new release, please post an announcement in the following channels:

* #discuss-rancher-feature-charts
* #discuss-rancher-feature-vsphere
* #discuss-rancher-k3s-rke2

### CODE REVIEW

**Comment by phillipsj** [comment]
@secustor thanks for the PR. We will review it next week.

**Comment by phillipsj** [comment]
@secustor can you rebase on the latest main branch? I will merge after that.

**Review by phillipsj — APPROVED** [review]
LGTM!

**Review by rosskirkpat — APPROVED** [review]
LGTM

**Pull request merged**
